##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_localization
description: A package that provides an easy way to add localization to your Flutter app.
version: 0.1.9
repository: https://github.com/robmllze/df_localization
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - configuration
  - locale
  - localization
  - state-management
  - translation

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_pod: ^0.13.3
  df_config: ^0.4.0

  path: ^1.9.0
  args: ^2.5.0
  yaml: ^3.1.2
  df_log: ^0.2.1
  google_generative_ai: ^0.4.6

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  ## -----------------------------------------------------------------------------

executables:
  gentr: gentr
  gentrsample: gentr
